Datatypes and variables

In [ ]:
print("Hello World")

Hello World


In [ ]:
print(5 + 4)

9


In [ ]:
num1 = 5
num2 = 4
sum = num1 + num2
print(sum)

9


In [ ]:
sum

9

In [ ]:
law = "Theresa"
tess = "'s"

In [ ]:
law

'Theresa'

In [ ]:
# print Theresa's
# what concatenation means
print(law + tess)
print("Theresa" + "'s")

Theresa's


In [ ]:
print("Theresa\'s")

Theresa's


In [ ]:
# Numerical Data
# Exponent = **

8


In [ ]:
name = "Tess"
age = 24
height = 5.5
is_student = True

In [ ]:
print("student Name:",name)
print("Studenet age:", age)
print("student height:", height)
print("is she a student:", is_student)

student Name: Tess
Studenet age: 24
student height: 5.5
is she a student: True


In [ ]:
# Checking for datatypes
print(type(name))
print(type(age))
print(type(height))
print(type(is_student))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [ ]:
type(name)

str

In [ ]:
# Undeerstanding the input function
name = input("Enter your name: ")
age = input("Enter your age: ")

print("Hello", name + ", you are", age , "years old")

Enter your name: Tess
Enter your age: 22
Hello Tess, you are 22 years old


In [ ]:
print(f"Hello {name}, you are {age} years old")

Hello Tess, you are 22 years old


In [ ]:
num1 = str(input("Enter your first number"))
num2 = str(input("Enter your second number"))

print(num1 + num2)

Enter your first number3
Enter your second number4
34


In [ ]:
num1

In [ ]:
num1 = float(input("Enter your first number:" ))
num2 = float(input("Enter your second number:" ))

print(num1 + num2)

Enter your first number:24
Enter your second number:23
47.0


In [ ]:
# Operators
# Arithmetic, compasrison, logical
a = 10
b = 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a // b)
print(a ** b)
print(a > b)

13
7
30
3.3333333333333335
1
3
1000
True


In [ ]:
# Example of logical operator
1 == 1
2 == 2

True

Bytes

In [ ]:
# they are used to  work with binary data
bytes(4)

b'\x00\x00\x00\x00'

In [ ]:
law = "Hello World"
my_bytes = bytes(law, "utf-8")
print(my_bytes)

b'Hello World'


In [ ]:
my_bytes = bytes([72, 65, 68])
print(my_bytes)

b'HAD'


In [ ]:
smileyBytes = bytearray('🙄', 'utf-8')

In [ ]:
smileyBytes[3] = int("85", 16)
print(smileyBytes)

bytearray(b'\xf0\x9f\x99\x85')


In [ ]:
smileyBytes.decode('utf-8')

'🙅'

Data Structures
- List
- sets
- tuples
- dictionaries
- slicing and indexing

datatypes you can index
- string
- list

In [ ]:
my_list =[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
law = "lawrencia"

In [ ]:
law[3]

'r'

In [ ]:
type(my_list)

list

In [ ]:
my_list = ["my", "name", "is", "tess"]

In [ ]:
my_list = [True, 1, [1, 2, 3, 4], "my"]

In [ ]:
len(my_list)

4

In [ ]:
my_list =[1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
len(my_list)

13

In [ ]:
print(my_list[:2])

[1, 2]


In [ ]:
print(my_list[2:])

[3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# my_list[start:stop:step]
print(my_list[1:10:2])

[2, 4, 6, 8, 10]


In [ ]:
my_list[-3]

8

List Comprehensions

In [ ]:
mylist = [1, 2, 3, 4, 5]
[2 * item for item in mylist]

[2, 4, 6, 8, 10]

List Comprehensions with filters

In [ ]:
mylist = list(range(100))
filteredlist = [item for item in mylist if item % 5 == 0]
filteredlist

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [ ]:
filterlist = [item for item in mylist if item % 6 == 0]
filterlist

[0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]

List Comprehensions with functions

In [ ]:
print("apple", "banana", "kiwi", sep = ", ")

apple, banana, kiwi


In [ ]:
cas = "apple banana kiwi"
print(cas.upper())

APPLE BANANA KIWI


In [ ]:
cas = "Apple Banana Kiwi"
print(cas.lower())

apple banana kiwi


In [ ]:
mystring = "My name is Theresah I live in Accra "
# mystring.split("/")

['My name is Theresah', ' I live in Accra ']

In [ ]:
mystring.split()

['My', 'name', 'is', 'Theresah/', 'I', 'live', 'in', 'Accra']

In [ ]:
def cleanword(word):
  return word.replace(" ", "").lower()
[cleanword(word) for word in mystring.split()]

['my', 'name', 'is', 'theresah/', 'i', 'live', 'in', 'accra']

In [ ]:
[cleanword(word) for word in mystring.split() if len(cleanword(word)) < 3]

['my', 'is', 'i', 'in']

Nested list comprehensions

In [ ]:
result =  []
for x in range(3):
  for y in range(2):
    result.append((x, y))
result

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1)]

In [ ]:
nlist = [(x, y) for x in range(3) for y in range(2)]
nlist

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1)]

In [ ]:
matrix = [[ y for y  in range(3)] for x in range(3)]
matrix

[[0, 1], [0, 1], [0, 1]]

In [ ]:
# create 2D matrix
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened = [item for row in matrix for item in row]
flattened

Sets

In [ ]:
my_set = {1, 2, 3, 1, 2, 4, 5, 6, 3, 4, 5, 7, 8, 9, 10}

In [ ]:
len(my_set)

10

In [ ]:
{1, 2, 3, 1, 2,} == {1, 2, 3}

True

In [ ]:
type(my_set)

set

In [ ]:
my_tuple = (1, 2, 3, 1, 2, 4, 5, 6, 3, 4, 5, 7, 8, 9, 10)

In [ ]:
len(my_tuple)

15

list methods
- append
- insert
- extend
- replace
- remove
- pop
- clear
- sort and reverse
- copy

In [ ]:
ap = [1, 2, 3, 4]

In [ ]:
ap.append(64)

In [ ]:
ap

[1, 2, 3, 4, 64]

In [ ]:
ap.insert(2, 7)

In [ ]:
ap

[1, 2, 7, 3, 4, 64]

In [ ]:
ap.extend([8, 9, 10])

In [ ]:
ap

[1, 2, 7, 3, 4, 64, 8, 9, 10]

In [ ]:
ap[5] = 5

In [ ]:
ap

[1, 2, 7, 3, 4, 5, 8, 9, 10]

In [ ]:
ap.insert(5, 6)

In [ ]:
ap

[1, 2, 7, 3, 4, 5, 6, 8, 6, 9, 10]

In [ ]:
ap.remove(7)

In [ ]:
law = {1, 2, 3, 4, 5, 6}
min = {4, 5, 6, 7, 8, 9}

In [ ]:
# add ten to set law
law.add(10)

In [ ]:
law.remove(3)

In [ ]:
ap

[1, 2, 3, 4, 5, 6, 9, 10]

In [ ]:
ap.pop()

9

In [ ]:
ap

[1, 2, 3, 4, 5, 6]

In [ ]:
ap.extend([7, 9, 8, 10])

In [ ]:
ap

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 7, 9, 8, 10]

In [ ]:
ap.sort(reverse = True)
ap

[10, 10, 9, 9, 8, 8, 7, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
# ap.clear()

In [ ]:
# create a list
num = [3, 4, 2, 1, 5]

In [ ]:
num.sort()
num

[1, 2, 3, 4, 5]

In [ ]:
num = [5, 3, 4, 2, 1]

In [ ]:
num.reverse()

In [ ]:
num

[1, 2, 4, 3, 5]

In [ ]:
num_copy = num.copy()
num_copy

[1, 2, 4, 3, 5]

Dictionaries

In [ ]:
my_dict = {
    "Tess":"is a girl",
    "law": "is a girl",
    "apple": "is a fruit"
}

In [ ]:
my_dict["Tess"]

'is a girl'

Control Flow
- simple if
- if ---- else
- elif (if ----- elif ---- else)
- nested if

In [ ]:
# An if state takes 2 items ie:
# the condition and the action to be performed
# eg
# if law so is something - condition
# print("this is is true of false")

She is an Adult


Simple if
- eg

In [ ]:
law =  25

if law > 25:
  print("She is an Adult")
if law == 25:
  print("She is a Young Adult")

She is a Young Adult


if -- else

In [ ]:
# runs one statement if the condition is true and another if the condition is false
if law >= 25:
  print("She is an Adult")
else:
  print("She is not an Adult")

She is an Adult


elif

In [ ]:
# Use multiple conditions to check the same sequence
if law >= 25:
  print("She is an Adult")
elif law >= 18:
  print("She is a Teenager")
else:
  print("She is a Child")

nested if

In [ ]:
# An if inside another if.
if law >= 25:
  print("She is an Adult")
  if law >= 20:
    print("She is a Young Adult")
else:
  print("She is not an Adult")

She is an Adult
She is a Young Adult


In [ ]:
a = 90
b = 60
c = 75
if a <= 80:
  print("You have passed")
  print("Excellent")
  if b <= 79:
    print("You performed averagely")
    if c <= 50:
      print("You failed")
else:
  print("It is False")

print("You are good")

It is False
You are good


Loops
- For
- While

In [ ]:
# a for loop goes through( or iterates over) a list, range, sequence
a = [1, 2, 3, 4, 5]
for number in a:
  print(number)

1
2
3
4
5


In [ ]:
for law in range(6):
  print(law)

0
1
2
3
4
5


In [ ]:
fruits = ["apple", "mango", "watermelon", "cherry"]
for tess in fruits:
  print("I like", tess)

I like apple
I like mango
I like watermelon
I like cherry


In [ ]:
# for law in range(2, 30):
#   if law % law == 0 & law % 1 == 0:
      # print(law)

While loop

In [ ]:
count = 0
while count <=5:
  print("Counting", count)
  count += 1

Counting 2
Counting 3
Counting 4
Counting 5


In [ ]:
count = count + 1
count = 2+1
count = 3+1
count = 4

In [ ]:
# first of you would have to set a count start(where you count will start from)
# you set a condition
# statements or block of code
# arithmetic instruction
count = 10
while count > 0:
  print("Counting",count)
  count -= 2

Counting 10
Counting 8
Counting 6
Counting 4
Counting 2


In [ ]:
count = count - 1
count = 5 - 1
count = 4 - 1
count = 3 - 1
count = 2 - 1
count = 1 - 1

In [ ]:
i = 0
while i < 3:
  print("While loop", i)
  i += 1

for i in range(5):
  print("Tess", i)

While loop 0
While loop 1
While loop 2
Tess 0
Tess 1
Tess 2
Tess 3
Tess 4


Break and continue

In [ ]:
# a break function stops a loop
count = 0
while count <= 10:
  if count == 7:
    break
  print("Count is", count)
  count += 1

Count is 0
Count is 1
Count is 2
Count is 3
Count is 4


In [ ]:
count = 10
while count > 1:
  if count == 5:
    break
  print("Count is", count)
  count -= 1

Count is 10
Count is 9
Count is 8
Count is 7
Count is 6


In [ ]:
count = 0
while count < 30:
  count += 1
  if count % 2 == 0 :
    continue
  print("Count is", count)

Count is 1
Count is 3
Count is 5
Count is 7
Count is 9
Count is 11
Count is 13
Count is 15
Count is 17
Count is 19
Count is 21
Count is 23
Count is 25
Count is 27
Count is 29


Functions

In [ ]:
# function is a block of reusable code that  performs a specific task
# def - which is the keyword to define the function
# name_of_function() - the name of the function
# parameter - a value that is passed into the function when it is called
# block code -
# return - which is the keyword to return a value from the function/ send the value back to where the function was called

def name_of_function():
  print("Tess")
  return value

In [ ]:
def greetings():
  print("Hello World")
greetings()

Hello World


In [ ]:
def greet_user(name):
  greetings = print("Hello", name)
  return

greet_user("Tess")

'law'

In [ ]:
# def add(a, b):
#     return a + b
# result = add(3, 5)
# print(result)

8


In [ ]:
def add(a, b):
  return a + b

In [ ]:
add(2, 4)

6

In [ ]:
def  mult(val):
  return 3 * val
mult(5)

15

In [ ]:
a = [1, 2, 3, 4, 5]

def num(mylist):
  mylist.pop()

num(a)
print(a)

[1, 2, 3, 4]


args (Arbitrary Positional Arguments) and kwargs (Arbitrary Text Arguments)

In [ ]:
# The *args syntax allows a function to accept any number of non-keyword (positional) arguments
def performopertions(*number):
  total =  sum(number)
  print(f"The sum of {number} is {total}")
performopertions(1, 2, 3)
performopertions(10, 20, 30, 40)

The sum of (1, 2, 3) is 6
The sum of (10, 20, 30, 40) is 100


In [ ]:
def performopertions(*args , **kwargs):
  print(args)
  print(kwargs)
  performopertions(1, 2, 3, operation = "sum")

Classes and Instances

In [ ]:
# a class in like a blueprint,  it tells python haow to make something.
# __init__ function runs when you make something new, it gives a name to what you are making
# self.name means what you are making should remember its name

class cat:
  def __init__(self, name):
    self.name = name
    self.legs = 4
    self.tail = True
    self.ear = 2

  def speak(self):
    print(self.name + "Meow")

In [ ]:
# the instance uses your blueprint to create something
my_cat = cat("Garfield")

In [ ]:
my_cat.speak()

Garfieldsays: Meow


In [ ]:
my_cat.legs

4

creating a menu using the class function

In [ ]:
class car:
  def __init__(self, brand, color):
    self.brand = brand
    self.color = color
    self.items = {}

  def add_vehicle(self, brand, color):
    self.items[brand] = color
    print(f"{brand} {color} added to the info")

  def info(self):
    print("Brand", self.brand)
    print("Color", self.color)

In [ ]:
my_car = car("brand", "color")

In [ ]:
my_car.add_vehicle("Toyota", "Red")
my_car.add_vehicle("KIA", "Blue")
my_car.add_vehicle("Corolla", "silver")
my_car.add_vehicle("Mercedez Benz", "black")
my_car.add_vehicle("Lexus", "white")

Toyota Red added to the info
KIA Blue added to the info
Corolla silver added to the info
Mercedez Benz black added to the info
Lexus white added to the info


In [ ]:
my_car.info()

Brand brand
Color color


In [ ]:
marks = int(input("Enter your marks: "))

if marks >= 80:
  print("You got an A")
  if marks >= 90:
    print("You are an Excellent student")



Enter your marks: 87
You got an A


In [ ]:
for i  in range(101):
  marks = i

  if marks >= 80:
    print("You got an A")
  elif marks >= 70:
    print("You got a B")
  elif marks >= 60:
    print("You got a C")
  elif marks >= 50:
    print("You got a D")
  else:
    print("You got a F")

Errors
- Syntax Error
- Logical Error

Exception
- performopertions
- TypeError
- ValueError
- NameError
- IndexError
- KeyError

In [ ]:
try:
  numerator = int(input("Enter a number to divide: "))
  denominator = int(input("Enter a number to divide by: "))
  result = numerator / denominator
except ZeroDivisionError:
  print("You can't divide by zero!")
except ValueError:
  print("Error: Invalid input. Please enter a valid number.")

Enter a number to divide: a
Error: Invalid input. Please enter a valid number.


Merging Dictionary
  - using union method

In [ ]:
my_dict = {
    "Tess":"is a girl",
    "law": "is a girl",
    "apple": "is a fruit"
}

In [ ]:
my_book = {
    "car":"is a green",
    "road": "is a long",
    "apple": "is a fruit"
}

In [ ]:
combined = my_dict | my_book
print(combined)

{'Tess': 'is a girl', 'law': 'is a girl', 'apple': 'is a fruit', 'car': 'is a green', 'road': 'is a long'}


the update method

In [ ]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}

In [ ]:
dict1.update(dict2)
print(dict1)

In [ ]:
dict3 ={**dict1, **dict2}
print(dict3)

{'a': 1, 'b': 3, 'c': 4}


Python Libraries is a collection of modules (pre-written code) that provide functions, classes, and tools to make coding easier.
  - Standard (built-in) Libraries
  - External (Third-party) Libraries

Math Library

In [ ]:
import math

In [ ]:
math.sqrt(16)

4.0

In [ ]:
math.pow(2, 3)

8.0

In [ ]:
math.factorial(4)

24

In [ ]:
math.floor(4.9)

4

In [ ]:
math.ceil(3.2)

4

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.e

2.718281828459045

Random

In [ ]:
import random

In [ ]:
random.random()

0.4728834361637746

In [ ]:
random.randint(1, 10)

2

In [ ]:
random.uniform(2, 3)

2.1223966286791667

In [ ]:
fruits = ["apple", "mango", "watermelon", "cherry"]
random.choice(fruits)

'cherry'

In [ ]:
random.shuffle(fruits)
fruits

['mango', 'cherry', 'apple', 'watermelon']

Statistics

In [ ]:
import statistics

In [ ]:
data = [10, 20, 30, 40, 50]

In [ ]:
statistics.mean(data)

30

In [ ]:
statistics.median(data)

30

In [ ]:
statistics.mode(data)

10

In [ ]:
statistics.stdev(data)

15.811388300841896

In [ ]:
statistics.variance(data)

250

Datatime

In [ ]:
from datetime import datetime, date, time, timedelta

In [ ]:
now = datetime.now()

In [ ]:
print("Current Datetime:", now)

Current Datetime: 2025-10-20 20:06:22.086335


In [ ]:
date.today()

datetime.date(2025, 10, 20)

In [ ]:
now.time()

datetime.time(20, 6, 22, 86335)

In [ ]:
datetime.now()

datetime.datetime(2025, 10, 20, 20, 12, 0, 383205)

Threads

In [ ]:
import threading

In [ ]:
def print_number():
  for i in range(1, 10):
    print(f"Number: {i}")


t = threading.Thread(target = print_number)
t.start()


t.join()
print("Main thred finished")

Number: 1
Number: 2
Number: 3
Number: 4
Number: 5
Number: 6
Number: 7
Number: 8
Number: 9
Main thred finished


importing a module or py file

In [ ]:
import cal

In [ ]:
cal.add(5, 6)

11

In [ ]:
cal.subtract(11, 8)

3

Reading and Writing a txt file

In [ ]:
file = open("example.txt", "r")  # 'r' = read mode
content = file.read()
print(content)
file.close()


In [ ]:
file = open("tess.txt", "w")
file.write("This myself")
file.close()

In [ ]:
file = open("tess.txt", "a")
file.write("\n I am a student.")
file.close()

In [ ]:
file = open("tess.txt", "r+")
print(file.read())
file.write("\n Welcome to Python programming.")
file.close()

This myself
 I am a student.


External Libraries
  - Numpy
  - Pandas

Numpy means numerical python
- Fast numerical computation
- Handling large arrays and matrices
- Performing mathematical operations efficiently
- Always install numpy in your IDE

In [ ]:
import numpy
import numpy as np

In [ ]:
# 1-dimentional array
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
# accessing element
print(arr1[0])

1


In [ ]:
# changing elements
arr1[3] = 9
arr1

array([1, 2, 3, 9, 5])

In [ ]:
# 2 dimentional array 2D

In [ ]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

🔹 1. Access by Row and Column Index

- NumPy uses zero-based indexing, meaning:

- First row = index 0

- First column = index 0

In [ ]:
# arr2[row, column]
print(arr2[0, 1])

2


In [ ]:
print(arr2[1, 2])

6


In [ ]:
print(arr2[1, 1])

5


In [ ]:
print(arr1.ndim)
print(arr2.ndim)

1
2


Creating Arrays with Built-in Functions
- Using arange()
- Using zeros() and ones()
-

In [ ]:
# np.arange(start, stop, step)
a = np.arange(0, 20, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [ ]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [ ]:
# np.linspace(start, stop, number of elements)
line = np.linspace(0, 5, 5)
line

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
# array operations (Vectorized)
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

In [ ]:
print(a + b)

[11 22 33 44]


In [ ]:
print(a - b)

[ -9 -18 -27 -36]


In [ ]:
print(a ** 2)

[ 1  4  9 16]


In [ ]:
print(b ** 2)

[ 100  400  900 1600]


In [ ]:
# Array methods
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
# summation
print(arr.sum())

15


In [ ]:
# Average
print(arr.mean())

In [ ]:
# minimum
print(arr.min())

1


In [ ]:
# maximum
print(arr.max())

5


In [ ]:
# Matrix Operators
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

In [ ]:
print(a + b)
print(a @ b)
print(np.dot(a, b))

[11 22 33 44]
300
300


In [ ]:
# shape and reshape
a = np.arange(0, 20, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# always the number of element you have in your  array before reshaping
# make sure it can evenly be divided by the new shape
print(a.reshape(5, 2))

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [6]:
import numpy
import numpy as np

In [ ]:
law = np.arange(2, 21, 2)
law

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
law.reshape(2, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

Arrays Attributes

In [15]:
a = numpy.array([[1, 2.7, 3], [4, 5, 6]])

In [9]:
print(a.shape)

(2, 3)


In [10]:
a.ndim

2

In [13]:
b = 7.8

In [11]:
a.size

6

In [16]:
a.dtype

dtype('float64')

In [17]:
arr = np.array([10, 20, 30, 40, 50])

In [19]:
print(arr[0])

10


In [20]:
print(arr[1:4])

[20 30 40]


In [21]:
print(arr[-1])

50


In [22]:
arr2d = np.array([[10, 20, 30], [40, 50, 60]])

In [30]:
# when slicing/indexing 2D arrays, [row, column]
print(arr2d[1, 0:2])

[40 50]


In [29]:
print(arr2d[0:2, 1:3])

[[20 30]
 [50 60]]


Boolean Indexing

In [36]:
law = np.array([15, 25, 35, 45, 55, 65])

In [ ]:
print(law[law > 35])

[45 55 65]


In [41]:
print([law > 35])

[array([False, False, False,  True,  True,  True])]


Saving and Loading arrays

In [42]:
ama = np.array([15, 25, 35, 45, 55, 65])

In [43]:
# When saving a array you write np.save("new_name_for_your_array_file.npy", name of you array(variable))
np.save("tess.npy", ama)

In [44]:
c = np.load("tess.npy")
print(c)

[15 25 35 45 55 65]


In [45]:
c.reshape(2, 3)

array([[15, 25, 35],
       [45, 55, 65]])

In [46]:
c.ndim

1

In [47]:
c.shape

(6,)

In [50]:
print(c.min())

15


Example 

In [61]:
temps = np.array([30,  32, 31, 29, 28])
days = np.array(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"])

In [54]:
print("Maximum Temperature:",np.max(temps))

Maximum Temperature: 32


In [63]:
print("Days with Temperature below 30C:",np.array(days)[np.array(temps < 30)])

Days with Temperature below 30C: ['Thursday' 'Friday']


In [62]:
print("Days with Temperature below 30C:", np.sum(temps < 30))

Days with Temperature below 30C: 2


In [ ]:
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

Enter first number: 78
Enter second number: 47
Enter third number: 69


In [ ]:
if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print("The largest number is:", largest)

The largest number is: 78.0


In [ ]:
n = int(input())
lst = []

for _ in range(n):
    cmd, *args = input().split()

    if cmd == "insert":
        lst.insert(int(args[0]), int(args[1]))
    elif cmd == "print":
        print(lst)
    elif cmd == "remove":
        lst.remove(int(args[0]))
    elif cmd == "append":
        lst.append(int(args[0]))
    elif cmd == "sort":
        lst.sort()
    elif cmd == "pop":
        lst.pop()
    elif cmd == "reverse":
        lst.reverse()
    else:
        print(f"Unknown command: {cmd}")


[]


### Pandas 
Pandas is a python library that was built in top of Numpy
it is designed for structured table (table, spreedsheets, CSVs(Comma separated values) etc)

In [1]:
import pandas as pd

In [22]:
# Series is a one-dimensional labeled array capable of holding data of any type
s = pd.Series([1, 3, 5, 7, 9], index=['a', 'b', 'c', 'd', 'e'])

In [9]:
print(s)

a    1
b    3
c    5
d    7
e    9
dtype: int64


In [10]:
print(s[2])

5


C:\Users\Law\AppData\Local\Temp\ipykernel_4780\3674811518.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2])


In [12]:
print(s["c"])

5


In [23]:
# A Dataframe is a two-dimensional labeled data structure with columns of potentially different types.
# You can think of it like a spreadsheet or SQL table.
# data = {
#     "name_of_column1":[what_you_want_to_store_in_column,],
#     "name_of_column2":[what_you_want_to_store_in_column,],
#     "name_of_column3":[what_you_want_to_store_in_column,],
#     "name_of_column4":[what_you_want_to_store_in_column,]
# }
law = {
    "Score":[90, 80, 70, 60],
    "Position":["1st", "2nd", "3rd", "4th"],
    "Grade":["A", "B", "C", "D"],
    "Age":[20, 21, 22, 23],
    "Name":["Tess", "Law", "Ama", "Esi"],
    "Course":["Math", "Science", "English", "Social Studies"]
}

ts = pd.DataFrame(law)

In [24]:
print(ts)

   Score Position Grade  Age  Name          Course
0     90      1st     A   20  Tess            Math
1     80      2nd     B   21   Law         Science
2     70      3rd     C   22   Ama         English
3     60      4th     D   23   Esi  Social Studies


Saving a DataFrame

In [26]:
ts.to_csv("students_scores.csv", index = False)

In [27]:
la = pd.read_csv("students_scores.csv")

Reading and Writing files 

In [28]:
print(la)

   Score Position Grade  Age  Name          Course
0     90      1st     A   20  Tess            Math
1     80      2nd     B   21   Law         Science
2     70      3rd     C   22   Ama         English
3     60      4th     D   23   Esi  Social Studies
