Datatypes and variables

In [ ]:
print("Hello World")

Hello World


In [ ]:
print(5 + 4)

9


In [ ]:
num1 = 5
num2 = 4
sum = num1 + num2
print(sum)

9


In [ ]:
sum

9

In [ ]:
law = "Theresa"
tess = "'s"

In [ ]:
law

'Theresa'

In [ ]:
# print Theresa's
# what concatenation means
print(law + tess)
print("Theresa" + "'s")

Theresa's


In [ ]:
print("Theresa\'s")

Theresa's


In [ ]:
# Numerical Data
# Exponent = **

8


In [ ]:
name = "Tess"
age = 24
height = 5.5
is_student = True

In [ ]:
print("student Name:",name)
print("Studenet age:", age)
print("student height:", height)
print("is she a student:", is_student)

student Name: Tess
Studenet age: 24
student height: 5.5
is she a student: True


In [ ]:
# Checking for datatypes
print(type(name))
print(type(age))
print(type(height))
print(type(is_student))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [ ]:
type(name)

str

In [ ]:
# Undeerstanding the input function
name = input("Enter your name: ")
age = input("Enter your age: ")

print("Hello", name + ", you are", age , "years old")

Enter your name: Tess
Enter your age: 22
Hello Tess, you are 22 years old


In [ ]:
print(f"Hello {name}, you are {age} years old")

Hello Tess, you are 22 years old


In [ ]:
num1 = str(input("Enter your first number"))
num2 = str(input("Enter your second number"))

print(num1 + num2)

Enter your first number3
Enter your second number4
34


In [ ]:
num1

In [ ]:
num1 = float(input("Enter your first number:" ))
num2 = float(input("Enter your second number:" ))

print(num1 + num2)

Enter your first number:24
Enter your second number:23
47.0


In [ ]:
# Operators
# Arithmetic, compasrison, logical
a = 10
b = 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a // b)
print(a ** b)
print(a > b)

13
7
30
3.3333333333333335
1
3
1000
True


In [ ]:
# Example of logical operator
1 == 1
2 == 2

True

Bytes

In [ ]:
# they are used to  work with binary data
bytes(4)

b'\x00\x00\x00\x00'

In [ ]:
law = "Hello World"
my_bytes = bytes(law, "utf-8")
print(my_bytes)

b'Hello World'


In [ ]:
my_bytes = bytes([72, 65, 68])
print(my_bytes)

b'HAD'


In [ ]:
smileyBytes = bytearray('🙄', 'utf-8')

In [ ]:
smileyBytes[3] = int("85", 16)
print(smileyBytes)

bytearray(b'\xf0\x9f\x99\x85')


In [ ]:
smileyBytes.decode('utf-8')

'🙅'

Data Structures
- List
- sets
- tuples
- dictionaries
- slicing and indexing

datatypes you can index
- string
- list

In [ ]:
my_list =[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
law = "lawrencia"

In [ ]:
law[3]

'r'

In [ ]:
type(my_list)

list

In [ ]:
my_list = ["my", "name", "is", "tess"]

In [ ]:
my_list = [True, 1, [1, 2, 3, 4], "my"]

In [ ]:
len(my_list)

4

In [ ]:
my_list =[1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
len(my_list)

13

In [ ]:
print(my_list[:2])

[1, 2]


In [ ]:
print(my_list[2:])

[3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# my_list[start:stop:step]
print(my_list[1:10:2])

[2, 4, 6, 8, 10]


In [ ]:
my_list[-3]

8

List Comprehensions

In [ ]:
mylist = [1, 2, 3, 4, 5]
[2 * item for item in mylist]

[2, 4, 6, 8, 10]

List Comprehensions with filters

In [ ]:
mylist = list(range(100))
filteredlist = [item for item in mylist if item % 5 == 0]
filteredlist

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [ ]:
filterlist = [item for item in mylist if item % 6 == 0]
filterlist

[0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]

List Comprehensions with functions

In [ ]:
print("apple", "banana", "kiwi", sep = ", ")

apple, banana, kiwi


In [ ]:
cas = "apple banana kiwi"
print(cas.upper())

APPLE BANANA KIWI


In [ ]:
cas = "Apple Banana Kiwi"
print(cas.lower())

apple banana kiwi


In [ ]:
mystring = "My name is Theresah I live in Accra "
# mystring.split("/")

['My name is Theresah', ' I live in Accra ']

In [ ]:
mystring.split()

['My', 'name', 'is', 'Theresah/', 'I', 'live', 'in', 'Accra']

In [ ]:
def cleanword(word):
  return word.replace(" ", "").lower()
[cleanword(word) for word in mystring.split()]

['my', 'name', 'is', 'theresah/', 'i', 'live', 'in', 'accra']

In [ ]:
[cleanword(word) for word in mystring.split() if len(cleanword(word)) < 3]

['my', 'is', 'i', 'in']

Nested list comprehensions

In [ ]:
result =  []
for x in range(3):
  for y in range(2):
    result.append((x, y))
result

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1)]

In [ ]:
nlist = [(x, y) for x in range(3) for y in range(2)]
nlist

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1)]

In [ ]:
matrix = [[ y for y  in range(3)] for x in range(3)]
matrix

[[0, 1], [0, 1], [0, 1]]

In [ ]:
# create 2D matrix
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened = [item for row in matrix for item in row]
flattened

Sets

In [ ]:
my_set = {1, 2, 3, 1, 2, 4, 5, 6, 3, 4, 5, 7, 8, 9, 10}

In [ ]:
len(my_set)

10

In [ ]:
{1, 2, 3, 1, 2,} == {1, 2, 3}

True

In [ ]:
type(my_set)

set

In [ ]:
my_tuple = (1, 2, 3, 1, 2, 4, 5, 6, 3, 4, 5, 7, 8, 9, 10)

In [ ]:
len(my_tuple)

15

list methods
- append
- insert
- extend
- replace
- remove
- pop
- clear
- sort and reverse
- copy

In [ ]:
ap = [1, 2, 3, 4]

In [ ]:
ap.append(64)

In [ ]:
ap

[1, 2, 3, 4, 64]

In [ ]:
ap.insert(2, 7)

In [ ]:
ap

[1, 2, 7, 3, 4, 64]

In [ ]:
ap.extend([8, 9, 10])

In [ ]:
ap

[1, 2, 7, 3, 4, 64, 8, 9, 10]

In [ ]:
ap[5] = 5

In [ ]:
ap

[1, 2, 7, 3, 4, 5, 8, 9, 10]

In [ ]:
ap.insert(5, 6)

In [ ]:
ap

[1, 2, 7, 3, 4, 5, 6, 8, 6, 9, 10]

In [ ]:
ap.remove(7)

In [ ]:
law = {1, 2, 3, 4, 5, 6}
min = {4, 5, 6, 7, 8, 9}

In [ ]:
# add ten to set law
law.add(10)

In [ ]:
law.remove(3)

In [ ]:
ap

[1, 2, 3, 4, 5, 6, 9, 10]

In [ ]:
ap.pop()

9

In [ ]:
ap

[1, 2, 3, 4, 5, 6]

In [ ]:
ap.extend([7, 9, 8, 10])

In [ ]:
ap

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 7, 9, 8, 10]

In [ ]:
ap.sort(reverse = True)
ap

[10, 10, 9, 9, 8, 8, 7, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
# ap.clear()

In [ ]:
# create a list
num = [3, 4, 2, 1, 5]

In [ ]:
num.sort()
num

[1, 2, 3, 4, 5]

In [ ]:
num = [5, 3, 4, 2, 1]

In [ ]:
num.reverse()

In [ ]:
num

[1, 2, 4, 3, 5]

In [ ]:
num_copy = num.copy()
num_copy

[1, 2, 4, 3, 5]

Dictionaries

In [ ]:
my_dict = {
    "Tess":"is a girl",
    "law": "is a girl",
    "apple": "is a fruit"
}

In [ ]:
my_dict["Tess"]

'is a girl'

Control Flow
- simple if
- if ---- else
- elif (if ----- elif ---- else)
- nested if

In [ ]:
# An if state takes 2 items ie:
# the condition and the action to be performed
# eg
# if law so is something - condition
# print("this is is true of false")

She is an Adult


Simple if
- eg

In [ ]:
law =  25

if law > 25:
  print("She is an Adult")
if law == 25:
  print("She is a Young Adult")

She is a Young Adult


if -- else

In [ ]:
# runs one statement if the condition is true and another if the condition is false
if law >= 25:
  print("She is an Adult")
else:
  print("She is not an Adult")

She is an Adult


elif

In [ ]:
# Use multiple conditions to check the same sequence
if law >= 25:
  print("She is an Adult")
elif law >= 18:
  print("She is a Teenager")
else:
  print("She is a Child")

nested if

In [ ]:
# An if inside another if.
if law >= 25:
  print("She is an Adult")
  if law >= 20:
    print("She is a Young Adult")
else:
  print("She is not an Adult")

She is an Adult
She is a Young Adult


In [ ]:
a = 90
b = 60
c = 75
if a <= 80:
  print("You have passed")
  print("Excellent")
  if b <= 79:
    print("You performed averagely")
    if c <= 50:
      print("You failed")
else:
  print("It is False")

print("You are good")

It is False
You are good


Loops
- For
- While

In [ ]:
# a for loop goes through( or iterates over) a list, range, sequence
a = [1, 2, 3, 4, 5]
for number in a:
  print(number)

1
2
3
4
5


In [ ]:
for law in range(6):
  print(law)

0
1
2
3
4
5


In [ ]:
fruits = ["apple", "mango", "watermelon", "cherry"]
for tess in fruits:
  print("I like", tess)

I like apple
I like mango
I like watermelon
I like cherry


In [ ]:
# for law in range(2, 30):
#   if law % law == 0 & law % 1 == 0:
      # print(law)

While loop

In [ ]:
count = 0
while count <=5:
  print("Counting", count)
  count += 1

Counting 2
Counting 3
Counting 4
Counting 5


In [ ]:
count = count + 1
count = 2+1
count = 3+1
count = 4

In [ ]:
# first of you would have to set a count start(where you count will start from)
# you set a condition
# statements or block of code
# arithmetic instruction
count = 10
while count > 0:
  print("Counting",count)
  count -= 2

Counting 10
Counting 8
Counting 6
Counting 4
Counting 2


In [ ]:
count = count - 1
count = 5 - 1
count = 4 - 1
count = 3 - 1
count = 2 - 1
count = 1 - 1

In [ ]:
i = 0
while i < 3:
  print("While loop", i)
  i += 1

for i in range(5):
  print("Tess", i)

While loop 0
While loop 1
While loop 2
Tess 0
Tess 1
Tess 2
Tess 3
Tess 4


Break and continue

In [ ]:
# a break function stops a loop
count = 0
while count <= 10:
  if count == 7:
    break
  print("Count is", count)
  count += 1

Count is 0
Count is 1
Count is 2
Count is 3
Count is 4


In [ ]:
count = 10
while count > 1:
  if count == 5:
    break
  print("Count is", count)
  count -= 1

Count is 10
Count is 9
Count is 8
Count is 7
Count is 6


In [ ]:
count = 0
while count < 30:
  count += 1
  if count % 2 == 0 :
    continue
  print("Count is", count)

Count is 1
Count is 3
Count is 5
Count is 7
Count is 9
Count is 11
Count is 13
Count is 15
Count is 17
Count is 19
Count is 21
Count is 23
Count is 25
Count is 27
Count is 29


Functions

In [ ]:
# function is a block of reusable code that  performs a specific task
# def - which is the keyword to define the function
# name_of_function() - the name of the function
# parameter - a value that is passed into the function when it is called
# block code -
# return - which is the keyword to return a value from the function/ send the value back to where the function was called

def name_of_function():
  print("Tess")
  return value

In [ ]:
def greetings():
  print("Hello World")
greetings()

Hello World


In [ ]:
def greet_user(name):
  greetings = print("Hello", name)
  return

greet_user("Tess")

'law'

In [ ]:
# def add(a, b):
#     return a + b
# result = add(3, 5)
# print(result)

8


In [ ]:
def add(a, b):
  return a + b

In [ ]:
add(2, 4)

6

In [ ]:
def  mult(val):
  return 3 * val
mult(5)

15

In [ ]:
a = [1, 2, 3, 4, 5]

def num(mylist):
  mylist.pop()

num(a)
print(a)

[1, 2, 3, 4]


args (Arbitrary Positional Arguments) and kwargs (Arbitrary Text Arguments)

In [ ]:
# The *args syntax allows a function to accept any number of non-keyword (positional) arguments
def performopertions(*number):
  total =  sum(number)
  print(f"The sum of {number} is {total}")
performopertions(1, 2, 3)
performopertions(10, 20, 30, 40)

The sum of (1, 2, 3) is 6
The sum of (10, 20, 30, 40) is 100


In [ ]:
def performopertions(*args , **kwargs):
  print(args)
  print(kwargs)
  performopertions(1, 2, 3, operation = "sum")

Classes and Instances

In [ ]:
# a class in like a blueprint,  it tells python haow to make something.
# __init__ function runs when you make something new, it gives a name to what you are making
# self.name means what you are making should remember its name

class cat:
  def __init__(self, name):
    self.name = name
    self.legs = 4
    self.tail = True
    self.ear = 2

  def speak(self):
    print(self.name + "Meow")

In [ ]:
# the instance uses your blueprint to create something
my_cat = cat("Garfield")

In [ ]:
my_cat.speak()

Garfieldsays: Meow


In [ ]:
my_cat.legs

4

creating a menu using the class function

In [ ]:
class car:
  def __init__(self, brand, color):
    self.brand = brand
    self.color = color
    self.items = {}

  def add_vehicle(self, brand, color):
    self.items[brand] = color
    print(f"{brand} {color} added to the info")

  def info(self):
    print("Brand", self.brand)
    print("Color", self.color)

In [ ]:
my_car = car("brand", "color")

In [ ]:
my_car.add_vehicle("Toyota", "Red")
my_car.add_vehicle("KIA", "Blue")
my_car.add_vehicle("Corolla", "silver")
my_car.add_vehicle("Mercedez Benz", "black")
my_car.add_vehicle("Lexus", "white")

Toyota Red added to the info
KIA Blue added to the info
Corolla silver added to the info
Mercedez Benz black added to the info
Lexus white added to the info


In [ ]:
my_car.info()

Brand brand
Color color


In [ ]:
marks = int(input("Enter your marks: "))

if marks >= 80:
  print("You got an A")
  if marks >= 90:
    print("You are an Excellent student")



Enter your marks: 87
You got an A


In [ ]:
for i  in range(101):
  marks = i

  if marks >= 80:
    print("You got an A")
  elif marks >= 70:
    print("You got a B")
  elif marks >= 60:
    print("You got a C")
  elif marks >= 50:
    print("You got a D")
  else:
    print("You got a F")

Errors
- Syntax Error
- Logical Error

Exception
- performopertions
- TypeError
- ValueError
- NameError
- IndexError
- KeyError

In [ ]:
try:
  numerator = int(input("Enter a number to divide: "))
  denominator = int(input("Enter a number to divide by: "))
  result = numerator / denominator
except ZeroDivisionError:
  print("You can't divide by zero!")
except ValueError:
  print("Error: Invalid input. Please enter a valid number.")

Enter a number to divide: a
Error: Invalid input. Please enter a valid number.


Merging Dictionary
  - using union method

In [ ]:
my_dict = {
    "Tess":"is a girl",
    "law": "is a girl",
    "apple": "is a fruit"
}

In [ ]:
my_book = {
    "car":"is a green",
    "road": "is a long",
    "apple": "is a fruit"
}

In [ ]:
combined = my_dict | my_book
print(combined)

{'Tess': 'is a girl', 'law': 'is a girl', 'apple': 'is a fruit', 'car': 'is a green', 'road': 'is a long'}


the update method

In [ ]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}

In [ ]:
dict1.update(dict2)
print(dict1)

In [ ]:
dict3 ={**dict1, **dict2}
print(dict3)

{'a': 1, 'b': 3, 'c': 4}


Python Libraries is a collection of modules (pre-written code) that provide functions, classes, and tools to make coding easier.
  - Standard (built-in) Libraries
  - External (Third-party) Libraries

Math Library

In [ ]:
import math

In [ ]:
math.sqrt(16)

4.0

In [ ]:
math.pow(2, 3)

8.0

In [ ]:
math.factorial(4)

24

In [ ]:
math.floor(4.9)

4

In [ ]:
math.ceil(3.2)

4

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.e

2.718281828459045

Random

In [ ]:
import random

In [ ]:
random.random()

0.4728834361637746

In [ ]:
random.randint(1, 10)

2

In [ ]:
random.uniform(2, 3)

2.1223966286791667

In [ ]:
fruits = ["apple", "mango", "watermelon", "cherry"]
random.choice(fruits)

'cherry'

In [ ]:
random.shuffle(fruits)
fruits

['mango', 'cherry', 'apple', 'watermelon']

Statistics

In [ ]:
import statistics

In [ ]:
data = [10, 20, 30, 40, 50]

In [ ]:
statistics.mean(data)

30

In [ ]:
statistics.median(data)

30

In [ ]:
statistics.mode(data)

10

In [ ]:
statistics.stdev(data)

15.811388300841896

In [ ]:
statistics.variance(data)

250

Datatime

In [ ]:
from datetime import datetime, date, time, timedelta

In [ ]:
now = datetime.now()

In [ ]:
print("Current Datetime:", now)

Current Datetime: 2025-10-20 20:06:22.086335


In [ ]:
date.today()

datetime.date(2025, 10, 20)

In [ ]:
now.time()

datetime.time(20, 6, 22, 86335)

In [ ]:
datetime.now()

datetime.datetime(2025, 10, 20, 20, 12, 0, 383205)

Threads

In [ ]:
import threading

In [ ]:
def print_number():
  for i in range(1, 10):
    print(f"Number: {i}")


t = threading.Thread(target = print_number)
t.start()


t.join()
print("Main thred finished")

Number: 1
Number: 2
Number: 3
Number: 4
Number: 5
Number: 6
Number: 7
Number: 8
Number: 9
Main thred finished


importing a module or py file

In [ ]:
import cal

In [ ]:
cal.add(5, 6)

11

In [ ]:
cal.subtract(11, 8)

3

Reading and Writing a txt file

In [ ]:
file = open("example.txt", "r")  # 'r' = read mode
content = file.read()
print(content)
file.close()


In [ ]:
file = open("tess.txt", "w")
file.write("This myself")
file.close()

In [ ]:
file = open("tess.txt", "a")
file.write("\n I am a student.")
file.close()

In [ ]:
file = open("tess.txt", "r+")
print(file.read())
file.write("\n Welcome to Python programming.")
file.close()

This myself
 I am a student.


External Libraries
  - Numpy
  - Pandas

Numpy means numerical python
- Fast numerical computation
- Handling large arrays and matrices
- Performing mathematical operations efficiently
- Always install numpy in your IDE

In [ ]:
import numpy
import numpy as np

In [ ]:
# 1-dimentional array
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
# accessing element
print(arr1[0])

1


In [ ]:
# changing elements
arr1[3] = 9
arr1

array([1, 2, 3, 9, 5])

In [ ]:
# 2 dimentional array 2D

In [ ]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

🔹 1. Access by Row and Column Index

- NumPy uses zero-based indexing, meaning:

- First row = index 0

- First column = index 0

In [ ]:
# arr2[row, column]
print(arr2[0, 1])

2


In [ ]:
print(arr2[1, 2])

6


In [ ]:
print(arr2[1, 1])

5


In [ ]:
print(arr1.ndim)
print(arr2.ndim)

1
2


Creating Arrays with Built-in Functions
- Using arange()
- Using zeros() and ones()
-

In [ ]:
# np.arange(start, stop, step)
a = np.arange(0, 20, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [ ]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [ ]:
# np.linspace(start, stop, number of elements)
line = np.linspace(0, 5, 5)
line

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
# array operations (Vectorized)
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

In [ ]:
print(a + b)

[11 22 33 44]


In [ ]:
print(a - b)

[ -9 -18 -27 -36]


In [ ]:
print(a ** 2)

[ 1  4  9 16]


In [ ]:
print(b ** 2)

[ 100  400  900 1600]


In [ ]:
# Array methods
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
# summation
print(arr.sum())

15


In [ ]:
# Average
print(arr.mean())

In [ ]:
# minimum
print(arr.min())

1


In [ ]:
# maximum
print(arr.max())

5


In [ ]:
# Matrix Operators
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

In [ ]:
print(a + b)
print(a @ b)
print(np.dot(a, b))

[11 22 33 44]
300
300


In [ ]:
# shape and reshape
a = np.arange(0, 20, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# always the number of element you have in your  array before reshaping
# make sure it can evenly be divided by the new shape
print(a.reshape(5, 2))

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [6]:
import numpy
import numpy as np

In [ ]:
law = np.arange(2, 21, 2)
law

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
law.reshape(2, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

Arrays Attributes

In [15]:
a = numpy.array([[1, 2.7, 3], [4, 5, 6]])

In [9]:
print(a.shape)

(2, 3)


In [10]:
a.ndim

2

In [13]:
b = 7.8

In [11]:
a.size

6

In [16]:
a.dtype

dtype('float64')

In [17]:
arr = np.array([10, 20, 30, 40, 50])

In [19]:
print(arr[0])

10


In [20]:
print(arr[1:4])

[20 30 40]


In [21]:
print(arr[-1])

50


In [22]:
arr2d = np.array([[10, 20, 30], [40, 50, 60]])

In [30]:
# when slicing/indexing 2D arrays, [row, column]
print(arr2d[1, 0:2])

[40 50]


In [29]:
print(arr2d[0:2, 1:3])

[[20 30]
 [50 60]]


Boolean Indexing

In [36]:
law = np.array([15, 25, 35, 45, 55, 65])

In [ ]:
print(law[law > 35])

[45 55 65]


In [41]:
print([law > 35])

[array([False, False, False,  True,  True,  True])]


Saving and Loading arrays

In [42]:
ama = np.array([15, 25, 35, 45, 55, 65])

In [43]:
# When saving a array you write np.save("new_name_for_your_array_file.npy", name of you array(variable))
np.save("tess.npy", ama)

In [44]:
c = np.load("tess.npy")
print(c)

[15 25 35 45 55 65]


In [45]:
c.reshape(2, 3)

array([[15, 25, 35],
       [45, 55, 65]])

In [46]:
c.ndim

1

In [47]:
c.shape

(6,)

In [50]:
print(c.min())

15


Example 

In [61]:
temps = np.array([30,  32, 31, 29, 28])
days = np.array(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"])

In [54]:
print("Maximum Temperature:",np.max(temps))

Maximum Temperature: 32


In [63]:
print("Days with Temperature below 30C:",np.array(days)[np.array(temps < 30)])

Days with Temperature below 30C: ['Thursday' 'Friday']


In [62]:
print("Days with Temperature below 30C:", np.sum(temps < 30))

Days with Temperature below 30C: 2


In [ ]:
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

Enter first number: 78
Enter second number: 47
Enter third number: 69


In [ ]:
if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print("The largest number is:", largest)

The largest number is: 78.0


In [ ]:
n = int(input())
lst = []

for _ in range(n):
    cmd, *args = input().split()

    if cmd == "insert":
        lst.insert(int(args[0]), int(args[1]))
    elif cmd == "print":
        print(lst)
    elif cmd == "remove":
        lst.remove(int(args[0]))
    elif cmd == "append":
        lst.append(int(args[0]))
    elif cmd == "sort":
        lst.sort()
    elif cmd == "pop":
        lst.pop()
    elif cmd == "reverse":
        lst.reverse()
    else:
        print(f"Unknown command: {cmd}")


[]


### Pandas 
Pandas is a python library that was built in top of Numpy
it is designed for structured table (table, spreedsheets, CSVs(Comma separated values) etc)

In [1]:
import pandas as pd

In [ ]:
# Series is a one-dimensional labeled array capable of holding data of any type
s = pd.Series([1, 3, 5, 7, 9], index = ['a', 'b', 'c', 'd', 'e'])

In [9]:
print(s)

a    1
b    3
c    5
d    7
e    9
dtype: int64


In [10]:
print(s[2])

5


C:\Users\Law\AppData\Local\Temp\ipykernel_4780\3674811518.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2])


In [12]:
print(s["c"])

5


In [5]:
l = pd.Series({'Apples': 50, 'Bananas': 100, 'Oranges': 80})
print(l)

Apples      50
Bananas    100
Oranges     80
dtype: int64


In [23]:
# A Dataframe is a two-dimensional labeled data structure with columns of potentially different types.
# You can think of it like a spreadsheet or SQL table.
# data = {
#     "name_of_column1":[what_you_want_to_store_in_column,],
#     "name_of_column2":[what_you_want_to_store_in_column,],
#     "name_of_column3":[what_you_want_to_store_in_column,],
#     "name_of_column4":[what_you_want_to_store_in_column,]
# }
law = {
    "Score":[90, 80, 70, 60],
    "Position":["1st", "2nd", "3rd", "4th"],
    "Grade":["A", "B", "C", "D"],
    "Age":[20, 21, 22, 23],
    "Name":["Tess", "Law", "Ama", "Esi"],
    "Course":["Math", "Science", "English", "Social Studies"]
}

ts = pd.DataFrame(law)

In [24]:
print(ts)

   Score Position Grade  Age  Name          Course
0     90      1st     A   20  Tess            Math
1     80      2nd     B   21   Law         Science
2     70      3rd     C   22   Ama         English
3     60      4th     D   23   Esi  Social Studies


Saving a DataFrame

In [26]:
ts.to_csv("students_scores.csv", index = False)

In [27]:
la = pd.read_csv("students_scores.csv")

Reading and Writing files 

In [28]:
print(la)

   Score Position Grade  Age  Name          Course
0     90      1st     A   20  Tess            Math
1     80      2nd     B   21   Law         Science
2     70      3rd     C   22   Ama         English
3     60      4th     D   23   Esi  Social Studies


In [ ]:
# Step 1: Create a DataFrame of 3 employees with columns Name, Salary, and Department.
# Step 2: Add a new column called Bonus = 10% of Salary.
# Step 3: Save it as "employees.csv".
# Step 4: Read "employees.csv" into a new DataFrame.
# Step 5: Display only employees with Salary above 3000.
# Step 6: Replace any missing values in Bonus with 0.
# Step 7: Save the updated DataFrame as "employees_updated.csv".

In [78]:
data = pd.DataFrame({
    "Name": ["Tess", "Law", "Ama", "Esi", "Corner"],
    "Salary": [5000, 6000, 5500, 7000, 5000],
    "Department": ["HR", "Finance", "IT", "Marketing", "Sales"],
    "Location": ["Accra", "Kumasi", "Accra", "Cape Coast", "Tamale"],
    "Email": ["Tess.gmail.com", "law.hotmail.com", "Ama.yahoo.com", "Esi.outlook.com", "Corner.aol.com"]
})
data.head(5)

Name  Salary Department    Location            Email
0    Tess    5000         HR       Accra   Tess.gmail.com
1     Law    6000    Finance      Kumasi  law.hotmail.com
2     Ama    5500         IT       Accra    Ama.yahoo.com
3     Esi    7000  Marketing  Cape Coast  Esi.outlook.com
4  Corner    5000      Sales      Tamale   Corner.aol.com

In [79]:
data["Bonus"] = data["Salary"] * 0.1
print(data)

     Name  Salary Department    Location            Email  Bonus
0    Tess    5000         HR       Accra   Tess.gmail.com  500.0
1     Law    6000    Finance      Kumasi  law.hotmail.com  600.0
2     Ama    5500         IT       Accra    Ama.yahoo.com  550.0
3     Esi    7000  Marketing  Cape Coast  Esi.outlook.com  700.0
4  Corner    5000      Sales      Tamale   Corner.aol.com  500.0


In [40]:
data["Bonus"].astype(int)
print(data)

     Name  Salary Department    Location  Bonus
0    Tess    5000         HR       Accra  500.0
1     Law    6000    Finance      Kumasi  600.0
2     Ama    5500         IT       Accra  550.0
3     Esi    7000  Marketing  Cape Coast  700.0
4  Corner    5000      Sales      Tamale  500.0


In [80]:
data.to_csv("employees.csv", index = False)

Data Exploration

In [81]:
df = pd.read_csv("employees.csv")
df.head(5)

Name  Salary Department    Location            Email  Bonus
0    Tess    5000         HR       Accra   Tess.gmail.com  500.0
1     Law    6000    Finance      Kumasi  law.hotmail.com  600.0
2     Ama    5500         IT       Accra    Ama.yahoo.com  550.0
3     Esi    7000  Marketing  Cape Coast  Esi.outlook.com  700.0
4  Corner    5000      Sales      Tamale   Corner.aol.com  500.0

In [83]:
df.head(2)

Name  Salary Department Location            Email  Bonus
0  Tess    5000         HR    Accra   Tess.gmail.com  500.0
1   Law    6000    Finance   Kumasi  law.hotmail.com  600.0

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        5 non-null      object 
 1   Salary      5 non-null      int64  
 2   Department  5 non-null      object 
 3   Location    5 non-null      object 
 4   Email       5 non-null      object 
 5   Bonus       5 non-null      float64
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes


In [33]:
df.shape

(5, 4)

In [34]:
df.describe()

Salary       Bonus
count     5.000000    5.000000
mean   4700.000000  470.000000
std    2729.468813  272.946881
min       0.000000    0.000000
25%    5000.000000  500.000000
50%    5500.000000  550.000000
75%    6000.000000  600.000000
max    7000.000000  700.000000

In [44]:
df["Salary"].count()

np.int64(5)

In [45]:
df["Salary"].mean()

np.float64(4700.0)

In [46]:
df["Salary"].sum()

np.int64(23500)

In [47]:
df["Salary"].min()

np.int64(0)

In [48]:
df

Name  Salary Department  Bonus
0    Tess    5000         HR  500.0
1     Law    6000    Finance  600.0
2     Ama    5500         IT  550.0
3     Esi    7000  Marketing  700.0
4  Corner       0      Sales    0.0

In [50]:
df["Salary"] > 3000

0     True
1     True
2     True
3     True
4    False
Name: Salary, dtype: bool

In [51]:
df[df["Salary"] > 3000]

Name  Salary Department  Bonus
0  Tess    5000         HR  500.0
1   Law    6000    Finance  600.0
2   Ama    5500         IT  550.0
3   Esi    7000  Marketing  700.0

##### Selecting and Filtering
    - selecting columns
    - selecting rows
    - filtering rows

In [ ]:
# Single columns
df["Name"]

In [ ]:
# Double columns
df[["Name", "Salary"]]

Name  Salary
0    Tess    5000
1     Law    6000
2     Ama    5500
3     Esi    7000
4  Corner       0

In [ ]:
# Filtering rows
df[df["Salary"] > 5000]

Name  Salary Department  Bonus
1  Law    6000    Finance  600.0
2  Ama    5500         IT  550.0
3  Esi    7000  Marketing  700.0

In [ ]:
df[df["Salary"] != 5000]

Name  Salary Department    Location            Email  Bonus
1  Law    6000    Finance      Kumasi  law.hotmail.com  600.0
2  Ama    5500         IT       Accra    Ama.yahoo.com  550.0
3  Esi    7000  Marketing  Cape Coast  Esi.outlook.com  700.0

In [89]:
# Filtering using the between method
df[df["Salary"].between(5000, 6000)]

Name  Salary Department Location            Email  Bonus
0    Tess    5000         HR    Accra   Tess.gmail.com  500.0
1     Law    6000    Finance   Kumasi  law.hotmail.com  600.0
2     Ama    5500         IT    Accra    Ama.yahoo.com  550.0
4  Corner    5000      Sales   Tamale   Corner.aol.com  500.0

In [93]:
# Filter by text using contains method
df[df["Name"].str.contains("C")]

Name  Salary Department Location           Email  Bonus
4  Corner    5000      Sales   Tamale  Corner.aol.com  500.0

In [92]:
df[df["Email"].str.contains("yahoo")]

Name  Salary Department Location          Email  Bonus
2  Ama    5500         IT    Accra  Ama.yahoo.com  550.0

In [ ]:
# Setting case to False 
df[df["Name"].str.contains("e", case = False)]

Name  Salary Department    Location  Bonus
0    Tess    5000         HR       Accra  500.0
3     Esi    7000  Marketing  Cape Coast  700.0
4  Corner    5000      Sales      Tamale  500.0

In [76]:
# Starts with method
df[df["Name"].str.startswith("a")]

Empty DataFrame
Columns: [Name, Salary, Department, Location, Bonus]
Index: []

In [87]:
# Ends with method
df[df["Email"].str.endswith("com")]

Name  Salary Department    Location            Email  Bonus
0    Tess    5000         HR       Accra   Tess.gmail.com  500.0
1     Law    6000    Finance      Kumasi  law.hotmail.com  600.0
2     Ama    5500         IT       Accra    Ama.yahoo.com  550.0
3     Esi    7000  Marketing  Cape Coast  Esi.outlook.com  700.0
4  Corner    5000      Sales      Tamale   Corner.aol.com  500.0

Filter list of values (isin)

In [104]:
df[df["Location"].isin(["Accra", "Kumasi"])].count()

Name          3
Salary        3
Department    3
Location      3
Email         3
Bonus         3
dtype: int64

In [102]:
df["Location"].isin(["Accra", "Kumasi"]).sum()

np.int64(3)

In [36]:
df[df["Department"] == "Finance"]

Name  Salary Department  Bonus
1  Law    6000    Finance  600.0

In [32]:
# Selecting rows; two types 
# - by index(positional)
# - by index label(name)

df.iloc[2]  # by index position

Name            Ama
Salary         5500
Department       IT
Bonus         550.0
Name: 2, dtype: object

In [33]:
# slicing by positional index
df.loc[2:4]  # by index label

Name  Salary Department  Bonus
2     Ama    5500         IT  550.0
3     Esi    7000  Marketing  700.0
4  Corner       0      Sales    0.0

In [30]:
df.loc[2]  # by index label

Name            Ama
Salary         5500
Department       IT
Bonus         550.0
Name: 2, dtype: object

In [34]:
# slicing by index label
df.loc[2:4]  # by index label

Name  Salary Department  Bonus
2     Ama    5500         IT  550.0
3     Esi    7000  Marketing  700.0
4  Corner       0      Sales    0.0

Multiple Conditions

In [45]:
df.head(5)

Name  Salary Department    Location  Bonus
0    Tess    5000         HR       Accra  500.0
1     Law    6000    Finance      Kumasi  600.0
2     Ama    5500         IT       Accra  550.0
3     Esi    7000  Marketing  Cape Coast  700.0
4  Corner    5000      Sales      Tamale  500.0

In [53]:
df[(df["Salary"] == 5000) & (df["Location"] == "Accra")]

Name  Salary Department Location  Bonus
0  Tess    5000         HR    Accra  500.0

In [54]:
df[(df["Salary"] == 5000) | (df["Location"] == "Accra")]

Name  Salary Department Location  Bonus
0    Tess    5000         HR    Accra  500.0
2     Ama    5500         IT    Accra  550.0
4  Corner    5000      Sales   Tamale  500.0

In [96]:
df[~df["Salary"] < 5000]

Name  Salary Department    Location            Email  Bonus
0    Tess    5000         HR       Accra   Tess.gmail.com  500.0
1     Law    6000    Finance      Kumasi  law.hotmail.com  600.0
2     Ama    5500         IT       Accra    Ama.yahoo.com  550.0
3     Esi    7000  Marketing  Cape Coast  Esi.outlook.com  700.0
4  Corner    5000      Sales      Tamale   Corner.aol.com  500.0

Cleaning Data

In [7]:
import pandas as pd

In [39]:
tess = pd.read_csv("Data.csv")
tess.head(5)

Game    Year             Genre       Publisher  \
0         Grand Theft Auto V  2014.0            Action  Rockstar Games   
1  Call of Duty: Black Ops 3  2015.0           Shooter      Activision   
2      Red Dead Redemption 2  2018.0  Action-Adventure  Rockstar Games   
3         Call of Duty: WWII  2017.0           Shooter      Activision   
4                    FIFA 18  2017.0            Sports       EA Sports   

   North America  Europe  Japan  Rest of World  Global  
0           6.06    9.71   0.60           3.02   19.39  
1           6.18    6.05   0.41           2.44   15.09  
2           5.26    6.21   0.21           2.26   13.94  
3           4.67    6.21   0.40           2.12   13.40  
4           1.27    8.64   0.15           1.73   11.80

In [3]:
tess.shape

(52, 9)

In [4]:
tess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Game           52 non-null     object 
 1   Year           45 non-null     float64
 2   Genre          52 non-null     object 
 3   Publisher      45 non-null     object 
 4   North America  52 non-null     float64
 5   Europe         52 non-null     float64
 6   Japan          52 non-null     float64
 7   Rest of World  52 non-null     float64
 8   Global         52 non-null     float64
dtypes: float64(6), object(3)
memory usage: 3.8+ KB


In [9]:
tess.columns

Index(['Game', 'Year', 'Genre', 'Publisher', 'North America', 'Europe',
       'Japan', 'Rest of World', 'Global'],
      dtype='object')

In [11]:
tess.memory_usage()

Index            132
Game             416
Year             416
Genre            416
Publisher        416
North America    416
Europe           416
Japan            416
Rest of World    416
Global           416
dtype: int64

Dealing with Null Values
- Filling
    - forward fill 
    - backward fill
    - replacing missing values is something of your choice 
- Dropping 

In [5]:
tess.isnull().sum()

Game             0
Year             7
Genre            0
Publisher        7
North America    0
Europe           0
Japan            0
Rest of World    0
Global           0
dtype: int64

Dealing will null values.
    - if the null values in a column is more than 50% of your entire dataset, you might have to drop the entire column

In [6]:
tess.tail(5)

Game    Year         Genre  \
47   Brothers in Arms: Furious 4  2019.0       Shooter   
48                    Cel Damage     NaN          Misc   
49  Woolfe: The Red Hood Diaries     NaN     Adventure   
50                  Dark Cloud 2     NaN  Role-Playing   
51            DC Universe Online  2013.0           MMO   

                    Publisher  North America  Europe  Japan  Rest of World  \
47                    Ubisoft            0.0     0.0    0.0            0.0   
48                        NaN            0.0     0.0    0.0            0.0   
49                        NaN            0.0     0.0    0.0            0.0   
50                        NaN            0.0     0.0    0.0            0.0   
51  Sony Online Entertainment            0.0     0.0    0.0            0.0   

    Global  
47     0.0  
48     0.0  
49     0.0  
50     0.0  
51     0.0

In [ ]:
tess["Japan"] = tess["Japan"].fillna(tess["Japan"].median())

In [12]:
tess.tail(5)

Game    Year         Genre  \
47   Brothers in Arms: Furious 4  2019.0       Shooter   
48                    Cel Damage  2015.0          Misc   
49  Woolfe: The Red Hood Diaries  2015.0     Adventure   
50                  Dark Cloud 2  2015.0  Role-Playing   
51            DC Universe Online  2013.0           MMO   

                    Publisher  North America  Europe  Japan  Rest of World  \
47                    Ubisoft            0.0     0.0    0.0            0.0   
48                        NaN            0.0     0.0    0.0            0.0   
49                        NaN            0.0     0.0    0.0            0.0   
50                        NaN            0.0     0.0    0.0            0.0   
51  Sony Online Entertainment            0.0     0.0    0.0            0.0   

    Global  
47     0.0  
48     0.0  
49     0.0  
50     0.0  
51     0.0

In [16]:
# filling using some specific values
tess["Year"] = tess["Year"].fillna(2015)

In [ ]:
# Fill with the mean, mode and median for specific columns
tess["Japan"] = tess["Japan"].fillna(tess["Japan"].mean())
tess["India"] = tess["India"].fillna(tess["India"].mode()[0]) or tess["India"] = tess["India"].fillna(tess["India"].mode().iloc[0])
tess["China"] = tess["China"].fillna(tess["China"].median())

In [ ]:
# fowrard fill
tess = tess.fillna(method = "ffill")

In [ ]:
# backward fill
tess = tess.fillna(method = "bfill")

columns = (axis = 1)
rows = (axis = 0)

In [ ]:
# to check null values in each column ( total null values per column )
tess.isnull().sum()

Game             0
Year             0
Genre            0
Publisher        0
North America    0
Europe           0
Japan            0
Rest of World    0
Global           0
dtype: int64

In [ ]:
# this is the sum of the null values in the entire dataframe segregated by columns
tess.isnull().sum()

Game             0
Year             0
Genre            0
Publisher        7
North America    0
Europe           0
Japan            0
Rest of World    0
Global           0
dtype: int64

In [ ]:
# this is a summ of all the null values in the entire dataframe
tess.isnull().sum().sum()

np.int64(7)

In [ ]:
# thi is to check if any row has null values
tess.isnull().any(axis = 0)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39     True
40    False
41    False
42     True
43     True
44     True
45    False
46    False
47    False
48     True
49     True
50     True
51    False
dtype: bool

In [20]:
tess[tess["Publisher"].isnull()]

Game    Year         Genre Publisher  \
39            A Boy and His Blob  2015.0      Platform       NaN   
42                 Another World  2015.0     Adventure       NaN   
43                  Ape Escape 2  2015.0      Platform       NaN   
44               Bee Tap Extreme  2015.0        Action       NaN   
48                    Cel Damage  2015.0          Misc       NaN   
49  Woolfe: The Red Hood Diaries  2015.0     Adventure       NaN   
50                  Dark Cloud 2  2015.0  Role-Playing       NaN   

    North America  Europe  Japan  Rest of World  Global  
39            0.0     0.0    0.0            0.0     0.0  
42            0.0     0.0    0.0            0.0     0.0  
43            0.0     0.0    0.0            0.0     0.0  
44            0.0     0.0    0.0            0.0     0.0  
48            0.0     0.0    0.0            0.0     0.0  
49            0.0     0.0    0.0            0.0     0.0  
50            0.0     0.0    0.0            0.0     0.0

In [19]:
tess["Publisher"].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39     True
40    False
41    False
42     True
43     True
44     True
45    False
46    False
47    False
48     True
49     True
50     True
51    False
Name: Publisher, dtype: bool

Dropping nulls 

In [ ]:
# removes all rows with any null values
tess.dropna()

In [ ]:
# Removes rows only if all the columns are null
tess.dropna(how = "all")

In [ ]:
tess.dropna(subset = ["Publisher"])

Sorting Values in Pandas

    - Groupby
    - sort values
    - summation of values
    - counting values 

In [1]:
import pandas as pd

In [2]:
data = {
'OrderID': [101,102,103,104,105,106,107,108,109,110],
'Customer': ['Ama','Kojo','Yaw','Ama','Esi','Kojo','Kofi','Abena','Yaw','Ama'],
'City': ['Accra','Kumasi','Accra','Takoradi','Accra','Kumasi','Accra','Takoradi','Kumasi','Accra'],
'Product': ['Laptop','Phone','Tablet','Laptop','Phone','Laptop','Tablet','Phone','Laptop','Tablet'],
'Quantity': [1,2,3,1,2,1,4,3,2,1],
'Price': [5000,2000,1500,5200,2100,5100,1550,2200,5300,1600],
'OrderDate': [
'2025-01-01','2025-01-03','2025-01-05','2025-01-06','2025-01-10',
'2025-01-12','2025-01-15','2025-01-18','2025-01-20','2025-01-22'
]
}

In [ ]:
orders = pd.DataFrame(data)
orders

TypeError: DataFrame.__init__() got an unexpected keyword argument 'parse_dates'

In [ ]:
# GroupBy is used to split the data into groups based on some criteria.
grouped = orders.groupby(["Product"])["Price"].sum()
grouped


In [ ]:
grouped = orders.groupby(["City"])["Quantity"].count()
grouped

City
Accra       5
Kumasi      3
Takoradi    2
Name: Quantity, dtype: int64

In [4]:
orders["Aveage"] = orders["Price"] / orders["Quantity"]

In [ ]:
result = (
    orders.groupby(["City"])
        .aggregate(
            Total_Quantity = ("Quantity", "sum"),
            Total_Price = ("Price", "sum"),
            Average_Price = ("Price", "mean")
            
    )
)
result

SyntaxError: positional argument follows keyword argument (57791504.py, line 9)

NameError: name 'Average_Price' is not defined

In [52]:
# Sort_values is used to sort the data in ascending or descending order based on one or more columns.
sorted = orders["Quantity"].sort_values(ascending = False)
sorted

6    4
2    3
7    3
1    2
8    2
4    2
0    1
3    1
5    1
9    1
Name: Quantity, dtype: int64

In [57]:
most_expensive = orders["Price"].sort_values(ascending = False)
most_expensive.tail(1)

2    1500
Name: Price, dtype: int64

In [61]:
# Sum is used to get the total sum of a column or multiple columns in a DataFrame.
Total_Rev = orders["Price"].sum()
print(Total_Rev)

31550


In [62]:
Total_items = orders["Quantity"].sum()
print(Total_items)

20


In [64]:
# Count is used to get the total count of non-null values in a column or multiple columns in a DataFrame.
total_orders = orders["OrderID"].count()
print(total_orders)

10


In [70]:
num = 2.678968
rn = round(num, 1)
rn

2.7

Joining DataFrames
- Using Concatrnation Method

In [1]:
import pandas as pd

In [9]:
data = {
'Name': ['Ama', 'Kojo', 'Yaw', 'Esi', 'Kofi'],
'Age': [25, None, 30, None, 40],
'City': ['Accra', 'Kumasi', None, 'Takoradi', None],
'Salary': [5000, 4200, None, 3900, None]
}

In [10]:
arc = {
"marital Status": ["Single", "Divorced", "Married", None, "Single"],
"Salary": [5000, 4200, None, 3900, None],
"No Children": [0, 2, 1, None, 3]
}

In [16]:
law  = pd.DataFrame(data)
tess = pd.DataFrame(arc)

In [17]:
law

Name   Age      City  Salary
0   Ama  25.0     Accra  5000.0
1  Kojo   NaN    Kumasi  4200.0
2   Yaw  30.0      None     NaN
3   Esi   NaN  Takoradi  3900.0
4  Kofi  40.0      None     NaN

In [18]:
tess

marital Status  Salary  No Children
0         Single  5000.0          0.0
1       Divorced  4200.0          2.0
2        Married     NaN          1.0
3           None  3900.0          NaN
4         Single     NaN          3.0

In [ ]:
# Vertical Stacking
pd.concat([law, tess],axis = 0)

Name   Age      City  Salary marital Status  No Children
0   Ama  25.0     Accra  5000.0            NaN          NaN
1  Kojo   NaN    Kumasi  4200.0            NaN          NaN
2   Yaw  30.0      None     NaN            NaN          NaN
3   Esi   NaN  Takoradi  3900.0            NaN          NaN
4  Kofi  40.0      None     NaN            NaN          NaN
0   NaN   NaN       NaN  5000.0         Single          0.0
1   NaN   NaN       NaN  4200.0       Divorced          2.0
2   NaN   NaN       NaN     NaN        Married          1.0
3   NaN   NaN       NaN  3900.0           None          NaN
4   NaN   NaN       NaN     NaN         Single          3.0

In [29]:
# Resetting index after vertical stacking
pd.concat([law, tess],axis = 0).reset_index(drop = True)

Name   Age      City  Salary marital Status  No Children
0   Ama  25.0     Accra  5000.0            NaN          NaN
1  Kojo   NaN    Kumasi  4200.0            NaN          NaN
2   Yaw  30.0      None     NaN            NaN          NaN
3   Esi   NaN  Takoradi  3900.0            NaN          NaN
4  Kofi  40.0      None     NaN            NaN          NaN
5   NaN   NaN       NaN  5000.0         Single          0.0
6   NaN   NaN       NaN  4200.0       Divorced          2.0
7   NaN   NaN       NaN     NaN        Married          1.0
8   NaN   NaN       NaN  3900.0           None          NaN
9   NaN   NaN       NaN     NaN         Single          3.0

In [27]:
# Horizontal Stacking
pd.concat([law, tess],axis = 1)

Name   Age      City  Salary marital Status  Salary  No Children
0   Ama  25.0     Accra  5000.0         Single  5000.0          0.0
1  Kojo   NaN    Kumasi  4200.0       Divorced  4200.0          2.0
2   Yaw  30.0      None     NaN        Married     NaN          1.0
3   Esi   NaN  Takoradi  3900.0           None  3900.0          NaN
4  Kofi  40.0      None     NaN         Single     NaN          3.0

Working with Dates and Times in Pandas

In [5]:
orders

OrderID Customer      City Product  Quantity  Price   OrderDate
0      101      Ama     Accra  Laptop         1   5000  2025-01-01
1      102     Kojo    Kumasi   Phone         2   2000  2025-01-03
2      103      Yaw     Accra  Tablet         3   1500  2025-01-05
3      104      Ama  Takoradi  Laptop         1   5200  2025-01-06
4      105      Esi     Accra   Phone         2   2100  2025-01-10
5      106     Kojo    Kumasi  Laptop         1   5100  2025-01-12
6      107     Kofi     Accra  Tablet         4   1550  2025-01-15
7      108    Abena  Takoradi   Phone         3   2200  2025-01-18
8      109      Yaw    Kumasi  Laptop         2   5300  2025-01-20
9      110      Ama     Accra  Tablet         1   1600  2025-01-22

In [19]:
# changing data type of a column
orders["OrderDate"] = pd.to_datetime(orders["OrderDate"], format = "%Y-%m-%d")

In [ ]:
orders

In [ ]:
orders["Year"] = orders["OrderDate"].dt.year
orders

In [ ]:
orders["Month"] = orders["OrderDate"].dt.month
orders

In [ ]:
orders["Day"] = orders["OrderDate"].dt.day
orders

In [ ]:
orders["Day_Of_The_Week"] = orders["OrderDate"].dt.day_name()
orders

In [ ]:
orders["Year"] = orders["OrderDate"].dt.year
orders["Month"] = orders["OrderDate"].dt.month
orders["Day"] = orders["OrderDate"].dt.day